config/routes.rb
Jshop::Application.routes.draw do
    match '/onlinedengi/:gateway_id/:order_id' => 'gateway/onlinedengi#show', :as => :onlinedengi
    match '/onlinedengi/result'  => 'gateway/onlinedengi#result',  :as => :onlinedengi_result
    match '/onlinedengi/success' => 'gateway/onlinedengi#success', :as => :onlinedengi_success
    match '/onlinedengi/fail'   => 'gateway/onlinedengi#fail',   :as => :onlinedengi_fail

  resources :products do
    member do
      get :rate
      post :rate
      post :create_review
    end
  end

  match '/product/:id/rate/:stars' => "products#rate"
  
  constraints :subdomain => 'blog' do
    scope :module => 'blog', :as => 'blog', :subdomain => 'blog' do
      resources :news, :controller => :blog_entries
    end
    match '/:year/:month/:day/:slug', :to => 'blog_entries#show', :as => :entry_permalink

    match '/:year(/:month)(/:day)', :to => 'blog_entries#archive', :as => :news_archive, :constraints => {:year => /(19|20)\d{2}/, :month => /[01]?\d/, :day => /[0-3]?\d/}

    match '/tag/:tag', :to => 'blog_entries#tag', :as => :tag
    match '/' => 'blog_entries#index'
  end
end

app/views/blog_entries/_blog.html.erb
<h2><%= link_to e.title, entry_permalink(e) %></h2>

<div class="date">
  <%= l( e.created_at.to_date, :format => :long) %>
</div>

<div class="body">
    <% if e.images.length == 1 %>
      <%= link_to(image_tag(e.images.first.attachment.url(:normal)), e.images.first.attachment.url(:large), :class=>'blog_image',:subdomain=>nil) %>
    <% end %>

  <%= raw e.body %>

  <% if e.images.length > 1 %>
      <div class="images">
          <% e.images.each do |image| %>
              <%= link_to(image_tag(image.attachment.url(:normal)), image.attachment.url(:large)) %>
          <% end %>
      </div>
   <% end %>
</div>

<% unless e.tag_list.empty? %>
  <%= render :partial => 'tag_list', :locals => {:e => e}  %>
<% end %>

<br class="clear" />

app/views/blog_entries/_news_archive.html.erb
<% unless @latest.blank? %>
    <h5><%= t(:recent_news) %></h5>
    <ul class="newsnav">
        <% @latest.each do |news| %>
            <li><%= link_to news.title, entry_permalink(news) %> <br />
            <small><%= I18n.l(news.created_at, :format => "%B %d %Y") %></small></li>
        <% end %>
    </ul>
<% end %>
<% unless @archives.blank? %>
    <h5><%= t(:news_archive) %></h5>
        <ul id="news-archive">
        <% @archives.to_a.reverse.each do |year, months_with_entries| %>
          <% d = Date.parse("1/#{year}") %>

          <li><h6><%= year %></h6>

            <ul class="months">
            <% months_with_entries.each do |month, entries| %>
              <% d = Date.parse("#{year}, #{month}") %>

              <li>
                <%= link_to I18n.l(d, :format => "%B"), news_archive_path(:year => d.year, :month => d.month), :class=>'month' %>

                <ul class="posts">
                  <% entries.each do |entry| %>
                    <li><%= link_to(entry.title, entry_permalink(entry)) %></li>
                  <% end %>
                </ul>
              </li>

            <% end %>
            </ul>
          </li>
        <% end %>
        </ul>
<% end %>

app/views/blog_entries/_tag_list.html.erb
<div class="tags">
  <%= t('tags') %>:
  <% e.tag_list.each do |tag| %>
    <%= link_to(tag, tag_path(tag)) %> 
  <% end %>
</div>

app/views/blog_entries/index.html.erb
<% content_for :sidebar do %>
   <div id="blog-sidebar">
     <%= render :partial => 'news_archive', :object => @archives %>
   </div>
<% end %>
<div id='standart_right_box'>

  <% if !@blog_entries.empty? %>

    <ul id="blog-entries">
      <% @blog_entries.each do |e| %>
        <li class="blog_entry">
          <%= render :partial => 'blog', :locals => {:e => e} %>
        </li>
      <% end %>
    </ul>

    <% if @blog_entries.respond_to? :total_pages %>
        <%= will_paginate(:page_links => false, :previous_label => "&#171; #{t('newer')}", :next_label => "#{t('older')} &#187;") %>
    <% end %>

  <% else %>
    <p id="no_entries"><%= t('no_blog_entries') %></p>
  <% end %>
  <br class="clearfloat" />
</div>

app/views/blog_entries/show.html.erb
<% content_for :sidebar do %>
  <div id="blog-sidebar">
    <%= render :partial => 'news_archive', :object => @news_archive %>
  </div>
<% end %>
<div id='standart_right_box'>
  <ul id="blog-entries">
    <li class="blog_entry">
      <%= render :partial => 'blog', :locals => {:e => @blog_entry} %>
    </li>
  </ul>
  <br class="clearfloat" />
</div>