config/routes.rb
Jshop::Application.routes.draw do
    match '/onlinedengi/:gateway_id/:order_id' => 'gateway/onlinedengi#show', :as => :onlinedengi
    match '/onlinedengi/result'  => 'gateway/onlinedengi#result',  :as => :onlinedengi_result
    match '/onlinedengi/success' => 'gateway/onlinedengi#success', :as => :onlinedengi_success
    match '/onlinedengi/fail'   => 'gateway/onlinedengi#fail',   :as => :onlinedengi_fail

  resources :products do
    member do
      get :rate
      post :rate
      post :create_review
    end
  end

  match '/product/:id/rate/:stars' => "products#rate"
  
  constraints :subdomain => 'blog' do
    scope :module => 'blog', :as => 'blog', :subdomain => 'blog' do
      resources :news, :controller => :blog_entries
    end
    match '/:year/:month/:day/:slug', :to => 'blog_entries#show', :as => :entry_permalink

    match '/:year(/:month)(/:day)', :to => 'blog_entries#archive', :as => :news_archive, :constraints => {:year => /(19|20)\d{2}/, :month => /[01]?\d/, :day => /[0-3]?\d/}

    match '/tag/:tag', :to => 'blog_entries#tag', :as => :tag
    match '/' => 'blog_entries#index'
  end
end

app/views/shared/comments/_comments.html.erb
<%= javascript_include_tag 'custom.js' %>
<div id="unit_tabs">
  <ul class="unit_tabs_label">
    <li><a href="#" rel="tab1">
											<span class="inner">
												<span class="left"></span>
												<span class="center">Комментарии Bemileo</span>
												<span class="right"></span>
											</span>
    </a>
    </li>
    <li><a href="#" rel="tab2">
											<span class="inner">
												<span class="left"></span>
												<span class="center">ВКонтакте</span>
												<span class="right"></span>
											</span>
    </a>
    </li>
    <li><a href="#" rel="tab3">
											<span class="inner">
												<span class="left"></span>
												<span class="center">Facebook</span>
												<span class="right"></span>
											</span>
    </a>
    </li>
    <li><a href="#" rel="tab4">
											<span class="inner">
												<span class="left"></span>
												<span class="center">Twitter</span>
												<span class="right"></span>
											</span>
    </a>
    </li>
  </ul>
  <div class="unit_tabs_content">
    <div id="tab1" class="page">
      <% if user_signed_in? %>
          <%= render :partial => 'shared/comments/form', :locals=>{:product => @product, :review => @review} %>
      <% end %>
      <div class="comments">
        <%= render :partial => 'shared/comments/reviews' %>
      </div>
    </div>
    <div id="tab2" class="page">
      <%= render :partial => 'shared/comments/vkontakte' %>
    </div>
    <div id="tab3" class="page">
      <%= render :partial => 'shared/comments/facebook' %>
    </div>
    <div id="tab4" class="page">
      <%= render :partial => 'shared/comments/twitter' %>
    </div>
  </div>
</div>

app/views/shared/comments/_facebook.html.erb
<div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:comments href="example.com" num_posts="15" width="595"></fb:comments>

app/views/shared/comments/_form.html.erb
<%= form_for review, :url => create_review_product_path(product), :html => {:method => :post} do |f| %>
  <%= render "shared/error_messages", :target => review %>

  <p class="review_review_field">
    <%= f.text_area :review, :wrap => "virtual", :rows => "10", :class => "arena" %>
  </p>

  <p class="review_submit">
    <%= f.submit I18n.t('submit_your_review'), :class => "button bg_darkfirst" %>
  </p>
<% end %>

app/views/shared/comments/_reviews.html.erb
<% @reviews.each do |review| %>
  <div class="enter_comm">
    <div class="usercomm">
      <span class="email" ><%= review.user.email if user_signed_in? %></span> |
      <%= l review.created_at, :format => :long %>
      <br />
      <p>
        <%= review.review %>
      </p>
    </div>
  </div>
  <br />
<% end %>

app/views/shared/comments/_twitter.html.erb
Twitter

app/views/shared/comments/_vkontakte.html.erb
<!-- Put this script tag to the <head> of your page -->
<% content_for :head do %>
    <%= javascript_include_tag 'http://userapi.com/js/api/openapi.js?34' %>
<% end %>
<script type="text/javascript">
  VK.init({apiId: 20003922, onlyWidgets: true});
</script>

<!-- Put this div tag to the place, where the Comments block will be -->
<div id="vk_comments"></div>
<script type="text/javascript">
VK.Widgets.Comments("vk_comments", {limit: 15, width: "595", attach: "*"});
</script>