config/routes.rb
Jshop::Application.routes.draw do
    match '/onlinedengi/:gateway_id/:order_id' => 'gateway/onlinedengi#show', :as => :onlinedengi
    match '/onlinedengi/result'  => 'gateway/onlinedengi#result',  :as => :onlinedengi_result
    match '/onlinedengi/success' => 'gateway/onlinedengi#success', :as => :onlinedengi_success
    match '/onlinedengi/fail'   => 'gateway/onlinedengi#fail',   :as => :onlinedengi_fail

  resources :products do
    member do
      get :rate
      post :rate
      post :create_review
    end
  end

  match '/product/:id/rate/:stars' => "products#rate"
  
  constraints :subdomain => 'blog' do
    scope :module => 'blog', :as => 'blog', :subdomain => 'blog' do
      resources :news, :controller => :blog_entries
    end
    match '/:year/:month/:day/:slug', :to => 'blog_entries#show', :as => :entry_permalink

    match '/:year(/:month)(/:day)', :to => 'blog_entries#archive', :as => :news_archive, :constraints => {:year => /(19|20)\d{2}/, :month => /[01]?\d/, :day => /[0-3]?\d/}

    match '/tag/:tag', :to => 'blog_entries#tag', :as => :tag
    match '/' => 'blog_entries#index'
  end
end

app/views/backup/shared/_admin_head.html.erb
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<title><%= "Spree #{t('administration')}: " %>
<%= t(controller.controller_name, :default => controller.controller_name.titleize) %></title>

<%= javascript_tag do %>
  ajax_urls = <%= raw({
    :product_search_json       => admin_products_url(:format => 'json'),
    :product_search_basic_json => admin_products_url(:format => 'json', :json_format => 'basic', :limit => 10),
    :user_search_basic_json    => admin_users_url(:format => 'json', :json_format => 'basic', :limit => 10)
  }.to_json) %>;

  strings = <%= raw(
    [:no_results, :type_to_search, :searching].
    inject({}){|memo, item| {item => t(item) }}.to_json )
  %>
<% end %>

<%= stylesheet_link_tag 'admin/admin-reset', 'admin/grids', 'admin/admin-typography', 'admin/admin-forms', 'admin/admin-tables', 'admin/admin', 'admin/autocomplete', 'admin/token-input', :cache => 'admin/admin-all' %>
<%= javascript_include_tag 'jquery-1.4.2.min.js', 'rails', 'jquery-ui', 'jquery.suggest', 'jquery.tokeninput.js', 'jquery.delayedobserver.js', :cache => 'jquery-admin-plugins' %>
<%= javascript_include_tag('jquery.template') unless controller.controller_name == "overview" %>
<%= javascript_include_tag 'admin', 'nested-attribute', 'zone', 'calculator', 'gateway' %>
<%= javascript_tag "$ = jQuery;" %>
<%= javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery? %>
<%= javascript_include_tag 'jquery.alerts/jquery.alerts.js' %>
<%= javascript_include_tag 'jquery.autocomplete.min.js' %>

<%= stylesheet_link_tag '/javascripts/jquery.alerts/jquery.alerts.css' %>
<%= stylesheet_link_tag '/javascripts/jquery.alerts/jquery.alerts.spree.css' %>
<%#= stylesheet_link_tag 'jquery.autocomplete.css'
%>

<%= javascript_tag "jQuery.alerts.dialogClass = 'spree';" %>
<%= raw unobtrusive_datepicker_includes %>
<%= yield :head %>

app/views/backup/shared/_ajax_cart_head.html.erb
<%= javascript_include_tag 'ajax_cart' %>

app/views/backup/shared/_basic_layout.html.erb
<%
if @body_class.nil?
  if content_for?(:sidebar)
    @body_class = 'two-col'
  else
    @body_class = 'one-col'
  end
end
 %>
<body class="<%= @body_class %>" id="<%= @body_id %>">
  <div id="header" class="container_bg">
    <div class="container">
    <div id="login-bar">
      <ul id="nav-bar">
        <%= render 'shared/nav_bar' %>
      </ul>
    </div>
  <%= logo %>
  </div>
  </div>

  <div id="wrapper" class="container">
    <% if content_for?(:sidebar) %>
    <div id="sidebar">
      <%= hook :sidebar do %>
        <%= yield :sidebar %>
      <% end %>
    </div>
    <% end %>

    <div id="content">
      <%= breadcrumbs(@taxon) if @taxon %>
      <% if flash.notice %>
      <div class="flash notice"><%= flash.notice %></div>
      <% end %>
      <% if flash[:error] %>
      <div class="flash errors"><%= flash[:error] %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render :partial => 'shared/footer'%>
  </div>

</body>

app/views/backup/shared/_filters.html.erb
<%= form_tag '', :method => :get, :id => 'sidebar_products_search' do  %>
  <% params[:search] ||= {} %>
  <input type="hidden" name="per_page" value="<%= params[:per_page] %>"/>

  <% filters = @taxon ? @taxon.applicable_filters : [ProductFilters.all_taxons] %>
  <% filters.each do |filter| %>
    <% labels = filter[:labels] || filter[:conds].map {|m,c| [m,m]} %>
    <% next if labels.empty? %>
    <div class="navigation">
      <span class="category"> <%= filter[:name] %> </span>
      <ul style="list-style-type:none; padding-left: 0px;" class="filter_choices">
        <% labels.each do |nm,val| %>
          <% label = "#{filter[:name]}_#{nm}".gsub(/\s+/,'_') %>
          <li class="nowrap">
            <input type="checkbox"
                   id="<%= label %>"
                   name="search[<%= filter[:scope].to_s %>][]"
                   value="<%= val %>"
                   <%= params[:search][filter[:scope]] && params[:search][filter[:scope]].include?(val.to_s) ? "checked" : "" %> />
            <label class="nowrap" for="<%= label %>"> <%= nm %> </label>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= submit_tag t(:search), :name => nil, :class => "submit_button", :style => "margin-top: 4px;" %>
<% end %>

app/views/backup/shared/_footer.html.erb
<table cellpadding="0" cellspacing="0" border="0" align="center" class="footer width_table">
  <tr>
    <td class="footer2_td">
      <img src="/images/p1.gif" border="0" alt="" width="162" height="26">
    </td>
    <td class="footer_td">
      <%= render 'shared/footer_menu'  %>
      <%= render 'shared/copyright'  %>
    </td>
  </tr>
</table> 
<%= render 'shared/google_analytics' %>

app/views/backup/shared/_footer_menu.html.erb
<span>
    <%= footer_menu_creator %>
</span>

app/views/backup/shared/_leanguage_bar.html.erb
<!--<table cellpadding="0" cellspacing="0" border="0" class="table2">
  <tr>
    <td class="languages">
      <table border="0" cellspacing="0" cellpadding="0" align="center">
	<tr>
	  <td style="padding:0px 0px 2px 0px;">
	    <%= t('language') %>:&nbsp;&nbsp;
	  </td>
	  <td style="width:100%;">
	    <%= render :partial => 'shared/locales_dropdown' %>
	  </td>
	</tr>
      </table>
    </td>
    <!--<td class="currencies">				
      <table border="0" cellspacing="0" cellpadding="0" align="center">
        <tr>
	  <td style="padding:0px 0px 2px 0px;"><%= t('currencies') %>:&nbsp;&nbsp;</td>
	  <td style="width:100%;">
	    <form name="currencies" action="http://localhost/oscommerce-2.3.1/index.php" method="get">
	      <select name="currency" onChange="this.form.submit();" class="select">
	        <option value="USD" selected="selected">US Dollar</option>
	        <option value="EUR">Euro</option>
	      </select>
	      <input type="hidden" name="osCsid" value="4d4eoqefhbpmel6tk4mg8ifo67">
	    </form>
	  </td>
        </tr>
      </table>
    </td>- ->
  </tr>
</table>-->

app/views/backup/shared/_nav_bar.html.erb
<table cellpadding="0" cellspacing="0" border="0">
  <tr>
    <td>
      <table cellpadding="0" cellspacing="0" border="0">
	<tr>
      <td class="logo" align="left">
	    <img src="/images/logo.gif" border="0" alt="" width="353" height="78">
	  </td>
	  <td class="navigation">
	    <table cellpadding="0" cellspacing="0" border="0" align="right" class="table">
              <tr>
		<td class="z1">
		  <table cellpadding="0" cellspacing="0" border="0" align="right">
		    <tr>
		      <td>
			<b>Shopping Cart&nbsp;</b>  now in your cart:
            <%= render :partial => 'orders/ajax_cart', :locals => {:order => current_order(true) } %>
			<%# link_to_cart %>
			</td>
		      </tr>
		    </table>
		  </td>
		</tr>
	      <tr>
		<td class="navigation2" align="right">	
		  <%= render 'shared/leanguage_bar' %>
		</td>
		</tr>
	      </table>
	    </td>
	  </tr>
	</table>
      </td>
    </tr>
    <tr>
      <td class="row_11">
	<table cellpadding="0" cellspacing="0" border="0">
	  <tr>
	    <td class="menu" id="td_menu_bar">
	      <table cellpadding="0" cellspacing="0" border="0">
		<tr>
		  <%= special_menu_creator %>
		</tr>
	      </table>
	    </td>
	  <td class="search">
	    <%= render 'shared/search' %>
	  </td>                
        </tr>
      </table>
    </td>
  </tr>
    <%= render 'shared/alerts' %>
</table>

app/views/backup/shared/_order_details.html.erb
<table class="index">
  <tbody id='line-items'>
    <tr>
      <%= hook :order_details_line_items_headers do %>
        <th><%= t('item_description') %></th>
        <th class="price"><%= t('price') %></th>
        <th class="qty"><%= t('qty') %></th>
        <th class="total"><span><%= t('total') %></span></th>
      <% end %>
    </tr>

    <% @order.line_items.each do |item| %>
      <tr>
        <%- locals = {:item => item} %>
        <%= hook :order_details_line_item_row, locals do %>
          <td width="300"><%=item.variant.product.name%> <%= "(" + variant_options(item.variant) + ")" unless item.variant .option_values.empty? %></td>
          <td class="price"><%= number_to_currency item.price %></td>
          <td class="qty"><%=item.quantity%></td>
          <td class="total"><span><%= number_to_currency (item.price * item.quantity)%></span></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
  <%= hook :order_details_subtotal do %>
    <tbody id='subtotal'>
      <tr class="total" id="subtotal-row">
        <td colspan="3"><b><%= t('subtotal') %>:</b></td>
        <td class="total"><span><%= number_to_currency @order.item_total %></span></td>
      </tr>
    </tbody>
  <% end %>
  <%= hook :order_details_adjustments do %>
    <tbody id="order-charges">
      <% @order.adjustments.each do |adjustment| %>
        <tr class="total">
          <td colspan="3"><strong><%= adjustment.label %></strong></td>
          <td class="total"><span><%= number_to_currency adjustment.amount %></span></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
  <%= hook :order_details_total do %>
    <tbody id='order-total'>
      <tr class="total">
        <td colspan="3"><b><%= t('order_total') %>:</b></td>
        <td class="total"><span id="order_total"><%= number_to_currency @order.total %></span></td>
      </tr>
    </tbody>
  <% end %>
</table>

app/views/backup/shared/_products.html.erb
<table cellpadding="0" cellspacing="0" border="0">

  <% if controller.controller_name == "products" %>
<%= render 'shared/main_page_banners' %>
  <% end %>

<tr>
<td id="products">
<%
  paginated_products = @searcher.products if params.key?(:keywords)
  paginated_products ||= products
%>
<% if products.empty? %>
  <%= t(:no_products_found) %>
<% elsif params.key?(:keywords) %>
  <h3><%= t(:search_results, :keywords => h(params[:keywords])) unless params[:keywords].blank? %></h3>
<% end %>
 
<% if products.any? %>
<table border="0" width="" cellspacing="0" cellpadding="0">
<% cc=0 %>

  <% products.each do |product| %>
    <% if Spree::Config[:show_zero_stock_products] || product.has_stock? %>
      <%= hook :products_list_item, {:product => product} do %>
	<% if cc==0 %>
	  <tr>
	<% end %>
      <td align="left"  style="width:1px;">
	<table cellpadding="0" cellspacing="0" border="0" class="prod2_table">
	  <tr>
	    <td class="prod2_td">
	      <table cellpadding="0" cellspacing="0" border="0">
		<tr>
		  <td class="pic2_padd">
 		    <table cellpadding="0" cellspacing="0" border="0" align="center" class="wrapper_pic_table">
		      <tr>
			<td class="wrapper_pic_td">
			  <%= link_to small_image(product), product %>
			</td>
		      </tr>
		    </table> 
  		  </td>
		</tr>
		<tr>
	  	  <td class="name name2_padd">
	    	    <%= link_to raw(product.name), product, :class => 'product_name' %>
	  	  </td>
		</tr>
		<tr>
	  	  <td class="price2_padd"><b>Our price:</b> 
		    <span class="productSpecialPrice">
		      <%= product_price(product) %>
		    </span>
	  	  </td>
		</tr>
		<tr>
	  	  <td class="button2_padd button2_marg">
		      <table cellpadding="0" cellspacing="0" border="0">
			<tr>
			  <td>
                <span class="link2" style="white-space: nowrap;">
                <%= link_to t("add_to_cart"), add_to_cart_path(:variant_id => product.master.id), :method => :put %>
                &nbsp;</span>
			  </td>
			  <td>
                <span class="link2">
			    <%= link_to t("details"), product %>
                </span>
			  </td>
			</tr>
		      </table>
	  	  </td>
		</tr>
	      </table>
	    </td>
	  </tr>
	</table>
	</td>
    <%# should be smaller than 5,  but counting starts from 0 %>
    <% if cc < 4 %>
        <td class="prod_line_y padd_vv prod_line_y-part">
          <img src="/images/spacer.gif" border="0" alt="" width="1" height="1">
        </td>
    <% end %>
	<% cc=cc+1 %>
	<% if cc==5 %>
	  </tr>
	<% end %>
	<% if cc==5 %>
	  <% cc=0 %>
	<% end %>
        <% end %>
    <% end %>
  <% end %>
</table>
<% end %>
</td>
</tr>
<tr>
<td>
 
<% if paginated_products.respond_to?(:total_pages)
      params.delete(:search)
      params.delete(:taxon)
      
%><%= will_paginate(paginated_products,
                    :previous_label => "&#171; #{t('previous')}",
                    :next_label => "#{t('next')} &#187;") %>
<% end %>

</td>
</tr>
</table>

app/views/backup/shared/_search.html.erb
<% @taxons = @taxon && @taxon.parent ? @taxon.parent.children : Taxon.roots  %>
<%= form_tag products_url, :method => :get do %>
	      <table border="0" cellspacing="4" cellpadding="0" align="right" id="search_table">
		<tr>
		  <!--<td class="td">Search:&nbsp;&nbsp;</td>-->
		  <td class="search_input-rep">
		    <table cellpadding="0" cellspacing="0" border="0" class="search_input-left">
		      <tr>
			<td class="search_input-right">
			  <%= select_tag :taxon, 
        options_for_select([[t(:all_departments), '']] + 
                              @taxons.map {|t| [t.name, t.id]}, 
                            @taxon ? @taxon.id : params[:taxon]), :class => "go" %>
			</td>
		      </tr>
		    </table>
		  </td>
            	  <td class="search_input-rep">
		    <table cellpadding="0" cellspacing="0" border="0" class="search_input-left">
		      <tr>
			<td class="search_input-right">
			  <%= text_field_tag :keywords, params[:keywords], :class => "go" %>
			</td>
		      </tr>
		    </table>
		  </td>
		<td><img src="/images/spacer.gif" border="0" alt="" width="7" height="1"></td>
		<td class="search_button-rep">
		  <table cellpadding="0" cellspacing="0" border="0" class="search_button-left">
		    <tr>
		      <td class="search_button-right">
			<%= image_submit_tag "/images/buttons/button_search_prod.gif", :name => nil %>
		      </td>
		    </tr>
		  </table>
		</td>
	      </tr>
	    </table>
<% end %>

app/views/backup/shared/_social_sharing.html.erb
<div>
  <%=t "share" %>
</div>
<div class="vkontakte">
  <script type="text/javascript"><!--
  document.write(VK.Share.button(false,{type: "round_nocount", text: "<%=t("save") %>"}));
  --></script>
</div>
<div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#appId=149359638466614&amp;xfbml=1"></script><fb:like href="<%= request.url %>" send="false" layout="button_count" width="450" show_faces="false" font=""></fb:like>
<div class="twitter">
  <a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-lang="<%= session[:locale] %>">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
</div>

app/views/backup/shared/_taxonomy.html.erb
<ul>
  <% taxonomy.children.each do |taxon| %>
    <li class="bg_list">
      <%= link_to taxon.name, seo_url(taxon) %>
      <%= render :partial => 'shared/taxonomy', :object=> taxon %>
    </li>
  <% end %>
</ul>

app/views/backup/shared/_user_form.html.erb
<p>
  <%= f.label :email, t("email") %><br />
  <%= f.text_field :email, :class => 'title'  %>
</p>
<div id="password-credentials">
  <p>
    <%= f.label :password, t("password") %><br />
    <%= f.password_field :password, :class => 'title'  %>
  </p>

  <p>
    <%= f.label :password_confirmation, t(:confirm_password) %><br />
    <%= f.password_field :password_confirmation, :class => 'title' %>
  </p>
</div>

<%= hook :signup_below_password_fields %>