config/routes.rb
Jshop::Application.routes.draw do
    match '/onlinedengi/:gateway_id/:order_id' => 'gateway/onlinedengi#show', :as => :onlinedengi
    match '/onlinedengi/result'  => 'gateway/onlinedengi#result',  :as => :onlinedengi_result
    match '/onlinedengi/success' => 'gateway/onlinedengi#success', :as => :onlinedengi_success
    match '/onlinedengi/fail'   => 'gateway/onlinedengi#fail',   :as => :onlinedengi_fail

  resources :products do
    member do
      get :rate
      post :rate
      post :create_review
    end
  end

  match '/product/:id/rate/:stars' => "products#rate"
  
  constraints :subdomain => 'blog' do
    scope :module => 'blog', :as => 'blog', :subdomain => 'blog' do
      resources :news, :controller => :blog_entries
    end
    match '/:year/:month/:day/:slug', :to => 'blog_entries#show', :as => :entry_permalink

    match '/:year(/:month)(/:day)', :to => 'blog_entries#archive', :as => :news_archive, :constraints => {:year => /(19|20)\d{2}/, :month => /[01]?\d/, :day => /[0-3]?\d/}

    match '/tag/:tag', :to => 'blog_entries#tag', :as => :tag
    match '/' => 'blog_entries#index'
  end
end

app/views/backup/orders/_ajax_cart.html.erb
<div id="ajax_cart_flash">
</div>

<div id="ajax_cart">
  <%= render :partial => 'orders/ajax_form', :locals => {:order => order} %>
</div>

app/views/backup/orders/_ajax_form.html.erb
<div id="ajax_cart" class=".total">
  <%= link_to_cart(t('total')) %>
</div>

app/views/backup/orders/_form.html.erb
<%= render "shared/error_messages", :target => @order %>
<table id="cart-detail">
  <thead>
    <tr>
      <%= hook :cart_items_headers do %>
        <th colspan="2"><%= t("item") %></th>
        <th><%= t("price") %></th>
        <th><%= t("qty") %></th>
        <th><%= t("total") %></th>
        <th></th>
      <% end %>
    </tr>
  </thead>
  <tbody id="line_items">
    <%= order_form.fields_for :line_items do |item_form| %>
      <%= render 'line_item', :variant => item_form.object.variant, :line_item => item_form.object, :item_form => item_form %>
    <% end %>
  </tbody>
</table>

app/views/backup/orders/_line_item.html.erb
<tr class="<%= cycle('', 'alt') %>">
  <td>
    <%- locals = {:item_form => item_form, :variant => variant, :line_item => line_item} %>
    <%= hook :cart_item_image, locals do %>
      <% if variant.images.length == 0 %>
        <%= small_image(variant.product) %>
      <% else %>
        <%=  image_tag variant.images.first.attachment.url(:small)   %>
      <% end %>
    <% end %>
  </td>
  <td>
    <%= hook :cart_item_description, locals do %>
      <h4><%= link_to variant.product.name,  product_path(variant.product) %></h4>
      <%= variant_options variant %>
      <%= truncate(variant.product.description, :length => 100, :omission => "...") %>
    <% end %>
  </td>
  <td>
    <%= hook :cart_item_price, locals do %>
      <%=  product_price(line_item) %>
    <% end %>
  </td>
  <td>
    <%= hook :cart_item_quantity, locals do %>
      <%= item_form.text_field :quantity, :size => 3, :class => "line_item_quantity" %>
    <% end %>
  </td>

  <td>
    <%= hook :cart_item_total, locals do %>
      <%= format_price(product_price(line_item, :format_as_currency => false) * line_item.quantity) unless line_item.quantity.nil? %>
    <% end %>
  </td>
  <td>
    <%= hook :cart_item_delete, locals do %>
      <%= link_to(image_tag('/images/admin/icons/delete.png'), '#', :class => 'delete') %>
    <% end %>
  </td>

</tr>

app/views/backup/orders/edit.html.erb
<% @body_id = 'cart' %>

<h1><%= t("shopping_cart")%></h1>

<% if @order.line_items.empty? %>

  <%= hook :empty_cart do %>
    <p><%= t("your_cart_is_empty") %></p>
    <p><%=link_to t("continue_shopping"), products_path, :class => 'button continue' %></p>
  <% end %>

<% else %>
  <%= hook :outside_cart_form do %>
    <%= form_for(@order, :url => update_cart_path, :html=>{:id=>'updatecart'}) do |order_form| %>
      <%= hook :inside_cart_form do %>

        <%= hook :cart_items do %>
          <%= render :partial => 'form', :locals => {:order_form => order_form} %>
        <% end %>

        <div id="subtotal">
          <h3 style="text-align:right;"><%= "#{t("subtotal")}: #{order_price(@order)}" %></h3>
          <div class="links">
            <span class="link2">
            <%= link_to t("update"), '#', :onclick => "$('form#updatecart').submit(); return false;" %>
            &nbsp;&nbsp;<%= link_to t("checkout"), checkout_path %>
            &nbsp;&nbsp;
            <%=link_to t("continue_shopping"), products_path %>
            </span>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
  
  <%= form_tag empty_cart_path, :method => :put do %>
    <p id="clear_cart_link" style="padding-top:4px;">
      <input type="submit" value="<%= t('empty_cart') %>" class="submit_button" />
    </p>
  <% end %>

<% end %>

app/views/backup/orders/show.html.erb
<div id="order">
  <%= link_to t('back_to_store'), products_path, :class=>'standart_link' %> 

  <% if params.has_key? :checkout_complete %>
  	<br/><br/>
  	<h3><%= t('thank_you_for_your_order') %></h3>         
  <% else %>
  	| <span class="standart_link"> <%= link_to t('my_account'), account_path if current_user %></span>
  <% end %>
  <br/><br/>

  <%= render :partial => 'shared/order_details', :locals => {:order => @order} %>

  <br/>
  <%= link_to t('back_to_store'), products_path, :class=>'standart_link' %>
</div>